[package]
name = "nom-rule"
version = "0.1.2"
authors = ["andylokandy"]
edition = "2021"
license = "MIT"
description = "A procedural macro for defining nom combinators in simple DSL"
homepage = "https://github.com/andylokandy/nom-rule"
repository = "https://github.com/andylokandy/nom-rule"
documentation = "https://docs.rs/nom-rule"
readme = "README.md"
keywords = ["nom", "parsing", "generator", "pest", "macro"]

[dependencies]
nom = "7"
nom-rule-bootstrap = { package = "nom-rule", version = "=0.1.1" }
syn = "1"
quote = "1"
pratt = "0.3"
proc-macro2 = "1"
proc-macro-error = "1"

[dev-dependencies]
logos = "0.12"

[lib]
proc-macro = true
